# Generated by Django 4.0.5 on 2022-06-22 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.IntegerField(unique=True)),
                ('amount_paid', models.IntegerField()),
                ('occupants_name', models.CharField(max_length=100)),
                ('occupants_email', models.EmailField(max_length=254)),
                ('occupants_occupation', models.CharField(max_length=50)),
                ('number_of_nights', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
    ]
